# Generated by Django 3.1.2 on 2020-11-27 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_jupyter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='management_jupyter_app.category', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
    ]
